export const DEFAULT_PRODUCT_CATEGORIES = [
    'SUMINISTRO',
    'REPUESTOS',
    'SERVICIOS',
    'LUBRICANTES',
    'FERRETERIA',
    'DOTACION',
    'EPP',
    'ALIMENTACION',
    'ALQUILER',
    'HERRAMIENTAS',
    'PAPELERIA',
    'ASEO',
    'MANTENIMIENTO'
];

export const PRODUCT_UNITS = [
    "UNIDAD - UND",
    "CAJA - CAJA",
    "CALORÍA (CAL)",
    "CENTÍMETRO (CM)",
    "CENTÍMETRO CUADRADO (CM²)",
    "CENTÍMETRO CÚBICO (CM³)",
    "DIAS - DIA",
    "ELECTRONVOLTIO (EV)",
    "GALÓN - GAL",
    "GRADO CELSIUS (°C)",
    "GRADO FAHRENHEIT (°F)",
    "GRAMO (G)",
    "JULIO (J)",
    "KELVIN (K)",
    "KILOGRAMO (KG)",
    "KILÓMETRO (KM)",
    "KILÓMETRO POR HORA (KM/H)",
    "LIBRA - LB",
    "LITRO - L",
    "METRO - M",
    "METRO CUADRADO (M²)",
    "METRO CÚBICO (M³)",
    "METRO POR SEGUNDO (M/S)",
    "MILÍMETRO (MM)",
    "MILÍMETRO CUADRADO (MM²)",
    "MILÍMETRO CÚBICO (MM³)",
    "MINUTOS - MIN",
    "MOL (MOL)",
    "NEWTON (N)",
    "ONZA - OZ",
    "PAQUETE",
    "PASCAL (PA)",
    "PIE (FT)",
    "PIE CUADRADO (FT²)",
    "PIE CÚBICO (FT³)",
    "PULGADA (IN)",
    "PULGADA CUADRADA (IN²)",
    "PULGADA CÚBICA (IN³)",
    "RADIAN (RAD)",
    "SEGUNDO (S)",
    "TONELADA - TON",
    "VATIO (W)"
];
